// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BigPlayController from "./big_play_controller"
application.register("big-play", BigPlayController)

import BlankSlateController from "./blank_slate_controller"
application.register("blank-slate", BlankSlateController)

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FollowController from "./follow_controller"
application.register("follow", FollowController)

import FolloweesController from "./followees_controller"
application.register("followees", FolloweesController)

import HeaderSearchController from "./header_search_controller"
application.register("header-search", HeaderSearchController)

import HeartController from "./heart_controller"
application.register("heart", HeartController)

import ImageUploadController from "./image_upload_controller"
application.register("image-upload", ImageUploadController)

import NormalPlaybackController from "./normal_playback_controller"
application.register("normal-playback", NormalPlaybackController)

import PlayerController from "./player_controller"
application.register("player", PlayerController)

import PlaylistController from "./playlist_controller"
application.register("playlist", PlaylistController)

import PlaylistFormController from "./playlist_form_controller"
application.register("playlist-form", PlaylistFormController)

import PlaylistSortController from "./playlist_sort_controller"
application.register("playlist-sort", PlaylistSortController)

import PlaylistUpdateController from "./playlist_update_controller"
application.register("playlist-update", PlaylistUpdateController)

import PlaylistsSortController from "./playlists_sort_controller"
application.register("playlists-sort", PlaylistsSortController)

import SaveController from "./save_controller"
application.register("save", SaveController)

import SubnavController from "./subnav_controller"
application.register("subnav", SubnavController)

import SvgCoverController from "./svg_cover_controller"
application.register("svg-cover", SvgCoverController)

import ToggleSettingController from "./toggle_setting_controller"
application.register("toggle-setting", ToggleSettingController)

import TracklistController from "./tracklist_controller"
application.register("tracklist", TracklistController)

import UserDropdownController from "./user_dropdown_controller"
application.register("user-dropdown", UserDropdownController)

import UserFavoritesController from "./user_favorites_controller"
application.register("user-favorites", UserFavoritesController)
