common: &default_settings
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  app_name: alonetone
  log_level: info
  apdex_t: 1.0

  distributed_tracing:
    enabled: false
  span_events:
    enabled: false

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500

  error_collector:
    enabled: true
    ignore_classes:
      - ActionController::RoutingError

development:
  <<: *default_settings
  enabled: false

test:
  <<: *default_settings
  enabled: false

production:
  <<: *default_settings
  enabled: true

staging:
  <<: *default_settings
  enabled: true
  app_name: alonetone (Staging)
